apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  type: NodePort
  externalIPs:
    - "[[HOST_IP]]"
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: webapp
