apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  type: NodePort
  externalIPs:
  - 192.168.1.102
  - 192.168.1.100
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webapp

