apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  type: NodePort
  externalIPs:
    - 172.17.0.47
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webapp
