apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  type: NodePort
  externalIPs:
    - 172.17.0.20
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: webapp
